# Generated by Django 2.0.5 on 2019-08-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('reg_number', models.CharField(max_length=50, unique=True, verbose_name='Регистрационный номер машины')),
            ],
        ),
    ]
