# Generated by Django 2.0.5 on 2019-08-13 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_publish',
            field=models.BooleanField(default=True),
        ),
    ]
